import Head from 'next/head'
import Image from 'next/image'
import logo from '../assets/img/logo.png'
import Link from 'next/link'
import { IoLocationSharp  } from 'react-icons/io5'
import { getProducts } from '../services/getProducts'
export default function Home() {
 
  return (
    <div className='main-container'>
      <Head>
        <title>FG Golosinas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href={'/catalog'}>
          <div className='image-container'>
            <Image src={logo} alt={''} fill={true} className={'image'}/>
          </div>
          <div className='main-btn-container'>
            <h4>Toca la imagen para ver el catálogo</h4>
          </div>
        </Link>
      </div>
      <div className='main-btn-container'>
      <button onClick={() => getProducts()}>asdsa</button>

          <a href="https://goo.gl/maps/BAApxbd1WneaYZv38">
            <IoLocationSharp  size={'2em'} color={'#000b76'}/>
            <p>Visitanos en 9 de Julio 310, Campo Quijano</p>
          </a>
      </div>
    </div>
  )
}
